Resources:
  Ec2Instance:
  Type: 'AWS::EC2::Instance'
  Properties:
    SecurityGroups:
      - Fn::ImportValue: launch-wizard-2
#      - !Ref InstanceSecurityGroup
    KeyName: AWS_EC2_Demo
    # you may need to find out what instance types are available in your region 
    # - use https://cloud-images.ubuntu.com/locator/ec2/
    ImageId: 'ami-065a2f32a35b7c52f' 

#  InstanceSecurityGroup:
#    Type: 'AWS::EC2::SecurityGroup'
#    Properties:
#      GroupDescription: Enable SSH access via port 22
#      SecurityGroupIngress:
#        - IpProtocol: tcp
#          FromPort: '22'
#          ToPort: '22'
#          CidrIp: 0.0.0.0/0