Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
      #  - launch-wizard-2
        - !Ref InstanceSecurityGroup
      KeyName: AWS_EC2_Demo
      # you may need to find out what instance types are available in your region 
      # - use https://cloud-images.ubuntu.com/locator/ec2/
      # Find ImageId from ap-northeast-2, and image type is ubuntu
      ImageId: 'ami-0de358223fd8dc276'
      InstanceType: t2.micro
  
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0