# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
#      - run:
#          name: install git first
#          command: yum install git -y
#      - run:
#          name: clone template file to docker.
#          command: git clone https://github.com/JehyeonHeo/CICD-learning-with-tools.git -b circleci-project-setup
#      - run:
#          name: Make AWS cloudformation stack.
#          command: >-
#            aws cloudformation update-stack
#            --template-body file://CICD-learning-with-tools/template.yml
#            --stack-name ec2-launch
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name ec2-launch

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["63:28:29:45:fb:80:dc:73:38:35:88:1f:5d:19:d5:a6"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
#      - create_infrastructure
      - configure_infrastructure