# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

commands:
  destroy_environment:
    #description: destroy environments when roll back is necessary.
    steps:
      - run: 
          command: >-
            aws cloudformation delete-stack
            --stack-name ec2-launch
          when: on_fail 

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
#      - run:
#          name: install git first
#          command: yum install git -y
#      - run:
#          name: clone template file to docker.
#          command: git clone https://github.com/JehyeonHeo/CICD-learning-with-tools.git -b circleci-project-setup
#      - run:
#          name: Make AWS cloudformation stack.
#          command: >-
#            aws cloudformation update-stack
#            --template-body file://CICD-learning-with-tools/template.yml
#            --stack-name ec2-launch
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name ec2-launch

  configure_infrastructure:
    docker:
      - image: alpine:3.11

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["2b:73:b3:46:e7:40:6b:87:b8:1b:c6:b1:29:64:25:7b"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml
      - destroy_environment

  smoke_test:
    docker: 
      - image: alpine:latest
    steps: 
      - run:
          name: upgrade packages
          command: apk upgrade
      - run:
          name: install curl
          command: apk add curl
      - run:
          name: website existing check
          command: |
            if curl -s --head "https://google333.com"
              then
                echo "It worked!"
              else
                echo "It failed"
                return 1
            fi

  smoke-test2:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: export TERM=xterm
      - checkout
      - run: 
          name: simulate error
          command: |
            return 1
      - destroy_environment

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - create_infrastructure
      - configure_infrastructure
#      - smoke_test
#      - smoke-test2:
#          requires:
#            - create_infrastructure