---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade apt packages."
  become: yes
  apt:
    upgrade: yes
    autoremove: yes
    
- name: "install nodejs package"
  become: yes 
  apt: 
    name: ['nodejs', 'npm']
    state: latest

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes

- name: Creates directory
  file:
    path: web
    state: directory

- name: "copy 'index.js' to remote server"
  copy:
    src: index.js
    dest: web/index.js

- name: "initiate 'index.js' server in remote server"
  become: yes
  shell: pm2 start web/index.js -f